version : '3.2'

services: 

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 09f6caaa-e69c-11ec-a08d-0242ac170002
    volumes: 
      - redis_cache:/data
    networks:
      - local

  nginx_server:
    image: nginx:latest
    restart: always
    ports: 
      - 8080:80
    volumes:
    - ./logs:/logs
    - ./config/server/default.conf:/etc/nginx/conf.d/default.conf
    - ./config/server/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - local
    depends_on:
      - redis
      - database
      - app_node_1
      - app_node_2
      - app

  app_node_1:
    container_name: app_node_1
    image: nginx:latest
    restart: always
    ports: 
      - 80
    volumes:
      - ./config/app/site.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app
    links:
      - app
    depends_on:
      - redis
      - database
      - app
    networks:
      - local

  app_node_2:
    container_name: app_node_2
    image: nginx:latest
    restart: always
    ports: 
      - 80
    volumes:
      - ./config/app/site.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app
    links:
      - app
    depends_on:
      - redis
      - database
      - app
    networks:
      - local

  app:
    container_name: app
    build: src
    restart: always
    volumes:
      - ./src:/app
      - ./config/fpm.conf:/usr/local/etc/php-fpm.d/www.conf  
    depends_on:
      - redis
      - database
    networks:
      - local
  
  database:
    image: mariadb:latest
    restart: unless-stopped
    tty: true
    volumes:
      - ./bd/mariadb:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_DATABASE=api
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - TZ=America/Sao_Paulo
    ports:
      - "3306:3306"
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  redis_cache:
    driver: local